### ISSUE TITLE
Register and install actions from config

### ISSUE THREAD

**Issue by aardschok** [mindbender-studio/launcher#24]
## Issue
Registering actions derived from the studio configuration to be accessible in the launcher

## Sub issue
It is debatable where to call `actions.register_defaullt_actions` and  `actions.register_config_actions`. This is entirely based on the approach of calling the launcher.  

**Option 1**
Do this in the `__init__` module but this would mean it would not be relying on `avalon.pipeline.find_config` but on the `os.environ`.

**Option 2**
Call the functions in the `Application.__init__`  method of the launcher but this would require `deregister_actions` for both default and config related actions. The plus side of this approach would be that the user can call the launcher from python without the need of first

## Motivation
At Colorbleed we want the user to be able to start a `Fusion Render Node` from the launcher but the location and specific commands will differ per studio it would be better call a function from within the configuration. 

## Solution
In our `actions` module we have use [`register_config_actions`](https://github.com/Colorbleed/launcher/blob/c7450ea10c2fd3a41c2058eb76e818c4b7a50547/launcher/actions.py#L43)  to checks for a `register_launcher_actions` and runs it if found.

Example of register_launcher_actions:
```python
def register_launcher_actions():
    """Register specific actions which should be accessible in the launcher"""

    # Register fusion actions
    from .fusion import rendernode
    pipeline.register_plugin(api.Action, rendernode.FusionRenderNode)
```

Example of application with configuration actions:
[![https://gyazo.com/2fe9b9b1afbef83e84cd933468a96529](https://i.gyazo.com/2fe9b9b1afbef83e84cd933468a96529.png)](https://gyazo.com/2fe9b9b1afbef83e84cd933468a96529)

**Comment by tokejepsen** [comment]
Has this issue been solved?

**Comment by aardschok** [comment]
Yes this has been solved see: [here](https://github.com/Colorbleed/launcher/pull/6) 
~~Just not merged in the getavalon I see :thinking: ~~

Correction my bad, seemed to have been merged in `getavalon/launcher` a few months ago:
[with this PR](https://github.com/getavalon/launcher/commit/89b6f620ad3bbccacbdbdaeb57629c5c176dd87c)
